[2022-08-31 15:33:43,539] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: gcs_2_bq_dag.gcs_2_bq_external_task manual__2022-08-31T15:33:39.083641+00:00 [queued]>
[2022-08-31 15:33:43,546] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: gcs_2_bq_dag.gcs_2_bq_external_task manual__2022-08-31T15:33:39.083641+00:00 [queued]>
[2022-08-31 15:33:43,546] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-08-31 15:33:43,546] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-08-31 15:33:43,546] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-08-31 15:33:43,557] {taskinstance.py:1259} INFO - Executing <Task(BigQueryCreateExternalTableOperator): gcs_2_bq_external_task> on 2022-08-31 15:33:39.083641+00:00
[2022-08-31 15:33:43,562] {standard_task_runner.py:52} INFO - Started process 7586 to run task
[2022-08-31 15:33:43,563] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'gcs_2_bq_dag', 'gcs_2_bq_external_task', 'manual__2022-08-31T15:33:39.083641+00:00', '--job-id', '206', '--raw', '--subdir', 'DAGS_FOLDER/gcs_2_bq_dag.py', '--cfg-path', '/tmp/tmphll7kuip', '--error-file', '/tmp/tmpos5wk3l7']
[2022-08-31 15:33:43,564] {standard_task_runner.py:77} INFO - Job 206: Subtask gcs_2_bq_external_task
[2022-08-31 15:33:43,600] {logging_mixin.py:109} INFO - Running <TaskInstance: gcs_2_bq_dag.gcs_2_bq_external_task manual__2022-08-31T15:33:39.083641+00:00 [running]> on host 0aad59a5352b
[2022-08-31 15:33:43,644] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=gcs_2_bq_dag
AIRFLOW_CTX_TASK_ID=gcs_2_bq_external_task
AIRFLOW_CTX_EXECUTION_DATE=2022-08-31T15:33:39.083641+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-31T15:33:39.083641+00:00
[2022-08-31 15:33:43,645] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-08-31 15:33:43,650] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/providers/google/cloud/hooks/bigquery.py:637: DeprecationWarning: This method is deprecated. Please use `BigQueryHook.create_empty_table` method with passing the `table_resource` object. This gives more flexibility than this method.
  DeprecationWarning,

[2022-08-31 15:33:43,651] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1226, in execute
    encryption_configuration=self.encryption_configuration,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 689, in create_external_table
    table = Table(table_ref=TableReference.from_string(external_project_dataset_table, project_id))
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/table.py", line 253, in from_string
    table_id, default_project=default_project, property_name="table_id"
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/_helpers.py", line 890, in _parse_3_part_id
    parts = _split_id(full_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/_helpers.py", line 877, in _split_id
    with_prefix = _PROJECT_PREFIX_PATTERN.match(full_id)
TypeError: expected string or bytes-like object
[2022-08-31 15:33:43,663] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=gcs_2_bq_dag, task_id=gcs_2_bq_external_task, execution_date=20220831T153339, start_date=20220831T153343, end_date=20220831T153343
[2022-08-31 15:33:43,677] {standard_task_runner.py:92} ERROR - Failed to execute job 206 for task gcs_2_bq_external_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1226, in execute
    encryption_configuration=self.encryption_configuration,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 689, in create_external_table
    table = Table(table_ref=TableReference.from_string(external_project_dataset_table, project_id))
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/table.py", line 253, in from_string
    table_id, default_project=default_project, property_name="table_id"
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/_helpers.py", line 890, in _parse_3_part_id
    parts = _split_id(full_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/_helpers.py", line 877, in _split_id
    with_prefix = _PROJECT_PREFIX_PATTERN.match(full_id)
TypeError: expected string or bytes-like object
[2022-08-31 15:33:43,696] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-08-31 15:33:43,725] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
