[2022-09-01 09:43:15,462] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: gcs_2_bq_dag.gcs_to_gcs_yellow_task manual__2022-09-01T09:00:00.470838+00:00 [queued]>
[2022-09-01 09:43:15,468] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: gcs_2_bq_dag.gcs_to_gcs_yellow_task manual__2022-09-01T09:00:00.470838+00:00 [queued]>
[2022-09-01 09:43:15,468] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-09-01 09:43:15,468] {taskinstance.py:1239} INFO - Starting attempt 8 of 8
[2022-09-01 09:43:15,468] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-09-01 09:43:15,479] {taskinstance.py:1259} INFO - Executing <Task(GCSToGCSOperator): gcs_to_gcs_yellow_task> on 2022-09-01 09:00:00.470838+00:00
[2022-09-01 09:43:15,483] {standard_task_runner.py:52} INFO - Started process 4488 to run task
[2022-09-01 09:43:15,485] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'gcs_2_bq_dag', 'gcs_to_gcs_yellow_task', 'manual__2022-09-01T09:00:00.470838+00:00', '--job-id', '293', '--raw', '--subdir', 'DAGS_FOLDER/gcs_2_bq_dag.py', '--cfg-path', '/tmp/tmpon34ezh6', '--error-file', '/tmp/tmp62y94phz']
[2022-09-01 09:43:15,486] {standard_task_runner.py:77} INFO - Job 293: Subtask gcs_to_gcs_yellow_task
[2022-09-01 09:43:15,528] {logging_mixin.py:109} INFO - Running <TaskInstance: gcs_2_bq_dag.gcs_to_gcs_yellow_task manual__2022-09-01T09:00:00.470838+00:00 [running]> on host 1c13e5bf3b2c
[2022-09-01 09:43:15,573] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=gcs_2_bq_dag
AIRFLOW_CTX_TASK_ID=gcs_to_gcs_yellow_task
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T09:00:00.470838+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-01T09:00:00.470838+00:00
[2022-09-01 09:43:15,574] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-09-01 09:43:15,813] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/transfers/gcs_to_gcs.py", line 277, in execute
    self._copy_source_without_wildcard(hook=hook, prefix=prefix)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/transfers/gcs_to_gcs.py", line 324, in _copy_source_without_wildcard
    if hook.exists(self.source_bucket, prefix):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 516, in exists
    blob = bucket.blob(blob_name=object_name)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/bucket.py", line 723, in blob
    generation=generation,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 222, in __init__
    name = _bytes_to_unicode(name)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/_helpers.py", line 389, in _bytes_to_unicode
    raise ValueError("%r could not be converted to unicode" % (value,))
ValueError: ['raw2/*'] could not be converted to unicode
[2022-09-01 09:43:15,823] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=gcs_2_bq_dag, task_id=gcs_to_gcs_yellow_task, execution_date=20220901T090000, start_date=20220901T094315, end_date=20220901T094315
[2022-09-01 09:43:15,836] {standard_task_runner.py:92} ERROR - Failed to execute job 293 for task gcs_to_gcs_yellow_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/transfers/gcs_to_gcs.py", line 277, in execute
    self._copy_source_without_wildcard(hook=hook, prefix=prefix)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/transfers/gcs_to_gcs.py", line 324, in _copy_source_without_wildcard
    if hook.exists(self.source_bucket, prefix):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 516, in exists
    blob = bucket.blob(blob_name=object_name)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/bucket.py", line 723, in blob
    generation=generation,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 222, in __init__
    name = _bytes_to_unicode(name)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/_helpers.py", line 389, in _bytes_to_unicode
    raise ValueError("%r could not be converted to unicode" % (value,))
ValueError: ['raw2/*'] could not be converted to unicode
[2022-09-01 09:43:15,858] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-09-01 09:43:15,878] {dagrun.py:628} WARNING - Failed to get task '<TaskInstance: gcs_2_bq_dag.bq_external_2_part_task manual__2022-09-01T09:00:00.470838+00:00 [removed]>' for dag 'gcs_2_bq_dag'. Marking it as removed.
[2022-09-01 09:43:15,887] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
