[2022-09-02 13:50:07,209] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: gcs_2_bq_dag.gcs_2_bq_populate_table manual__2022-09-02T13:44:24.787187+00:00 [queued]>
[2022-09-02 13:50:07,216] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: gcs_2_bq_dag.gcs_2_bq_populate_table manual__2022-09-02T13:44:24.787187+00:00 [queued]>
[2022-09-02 13:50:07,216] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-09-02 13:50:07,216] {taskinstance.py:1239} INFO - Starting attempt 2 of 2
[2022-09-02 13:50:07,216] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-09-02 13:50:07,226] {taskinstance.py:1259} INFO - Executing <Task(BigQueryInsertJobOperator): gcs_2_bq_populate_table> on 2022-09-02 13:44:24.787187+00:00
[2022-09-02 13:50:07,230] {standard_task_runner.py:52} INFO - Started process 17729 to run task
[2022-09-02 13:50:07,232] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'gcs_2_bq_dag', 'gcs_2_bq_populate_table', 'manual__2022-09-02T13:44:24.787187+00:00', '--job-id', '402', '--raw', '--subdir', 'DAGS_FOLDER/gcs_2_bq_dag.py', '--cfg-path', '/tmp/tmpb1g43hv8', '--error-file', '/tmp/tmpwyjrsrc1']
[2022-09-02 13:50:07,233] {standard_task_runner.py:77} INFO - Job 402: Subtask gcs_2_bq_populate_table
[2022-09-02 13:50:07,271] {logging_mixin.py:109} INFO - Running <TaskInstance: gcs_2_bq_dag.gcs_2_bq_populate_table manual__2022-09-02T13:44:24.787187+00:00 [running]> on host 6aef44a1cff5
[2022-09-02 13:50:07,319] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=gcs_2_bq_dag
AIRFLOW_CTX_TASK_ID=gcs_2_bq_populate_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-02T13:44:24.787187+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-02T13:44:24.787187+00:00
[2022-09-02 13:50:07,320] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-09-02 13:50:07,321] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-09-02 13:50:07,325] {bigquery.py:1637} INFO - Inserting job ***_gcs_2_bq_dag_gcs_2_bq_populate_table_2022_09_02T13_44_24_787187_00_00_da734f0e736df159563d22f1cb10cc39
[2022-09-02 13:50:09,860] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2287, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2253, in _submit_job
    job_id=job_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1639, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1447, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1437, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 727, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Invalid value: Error while reading data, error message: Failed to expand table polynomial-land.trips_data_all.temp_table_dc3cfb0c-cf73-4358-b54e-f609583a5a65_source with file pattern gs://dtc_data_lake_polynomial-land/raw2/yellow/yellow_tripdata_2019-01.parquet: matched no files. File: gs://dtc_data_lake_polynomial-land/raw2/yellow/yellow_tripdata_2019-01.parquet at [3:13]

(job ID: airflow_gcs_2_bq_dag_gcs_2_bq_populate_table_2022_09_02T13_44_24_787187_00_00_da734f0e736df159563d22f1cb10cc39)

                                       -----Query Job SQL Follows-----                                       

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:
   2:            DROP TABLE IF EXISTS polynomial-land.trips_data_all.temp_table; 
   3:            LOAD DATA INTO polynomial-land.trips_data_all.temp_table 
   4:            FROM FILES ( 
   5:              format = 'PARQUET', 
   6:              uris = ['gs://dtc_data_lake_polynomial-land/raw2/yellow/yellow_tripdata_2019-01.parquet'] 
   7:            );
   8:
   9:            INSERT INTO polynomial-land.trips_data_all.yellow_external_table(
  10:              VendorID,
  11:              tpep_pickup_datetime,
  12:              tpep_dropoff_datetime,
  13:              passenger_count,
  14:              trip_distance,
  15:              RatecodeID,
  16:              store_and_fwd_flag,
  17:              PULocationID,
  18:              DOLocationID,
  19:              payment_type,
  20:              fare_amount,
  21:              extra,
  22:              mta_tax,
  23:              tip_amount
  24:              ,tolls_amount
  25:              ,improvement_surcharge
  26:              ,total_amount
  27:              ,congestion_surcharge
  28:              ,airport_fee
  29:              )
  30:                SELECT 
  31:                VendorID,
  32:              tpep_pickup_datetime,
  33:              tpep_dropoff_datetime,
  34:              passenger_count,
  35:              trip_distance,
  36:              RatecodeID,
  37:              store_and_fwd_flag,
  38:              PULocationID,
  39:              DOLocationID,
  40:              payment_type,
  41:              fare_amount,
  42:              extra,
  43:              mta_tax,
  44:              tip_amount,
  45:              tolls_amount,
  46:              improvement_surcharge,
  47:              total_amount,
  48:              congestion_surcharge,
  49:              CAST(airport_fee AS FLOAT64) as airport_fee
  50:            FROM polynomial-land.trips_data_all.temp_table;
  51:  
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
[2022-09-02 13:50:09,871] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=gcs_2_bq_dag, task_id=gcs_2_bq_populate_table, execution_date=20220902T134424, start_date=20220902T135007, end_date=20220902T135009
[2022-09-02 13:50:09,882] {standard_task_runner.py:92} ERROR - Failed to execute job 402 for task gcs_2_bq_populate_table
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2287, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2253, in _submit_job
    job_id=job_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1639, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1447, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1437, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 727, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Invalid value: Error while reading data, error message: Failed to expand table polynomial-land.trips_data_all.temp_table_dc3cfb0c-cf73-4358-b54e-f609583a5a65_source with file pattern gs://dtc_data_lake_polynomial-land/raw2/yellow/yellow_tripdata_2019-01.parquet: matched no files. File: gs://dtc_data_lake_polynomial-land/raw2/yellow/yellow_tripdata_2019-01.parquet at [3:13]

(job ID: airflow_gcs_2_bq_dag_gcs_2_bq_populate_table_2022_09_02T13_44_24_787187_00_00_da734f0e736df159563d22f1cb10cc39)

                                       -----Query Job SQL Follows-----                                       

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:
   2:            DROP TABLE IF EXISTS polynomial-land.trips_data_all.temp_table; 
   3:            LOAD DATA INTO polynomial-land.trips_data_all.temp_table 
   4:            FROM FILES ( 
   5:              format = 'PARQUET', 
   6:              uris = ['gs://dtc_data_lake_polynomial-land/raw2/yellow/yellow_tripdata_2019-01.parquet'] 
   7:            );
   8:
   9:            INSERT INTO polynomial-land.trips_data_all.yellow_external_table(
  10:              VendorID,
  11:              tpep_pickup_datetime,
  12:              tpep_dropoff_datetime,
  13:              passenger_count,
  14:              trip_distance,
  15:              RatecodeID,
  16:              store_and_fwd_flag,
  17:              PULocationID,
  18:              DOLocationID,
  19:              payment_type,
  20:              fare_amount,
  21:              extra,
  22:              mta_tax,
  23:              tip_amount
  24:              ,tolls_amount
  25:              ,improvement_surcharge
  26:              ,total_amount
  27:              ,congestion_surcharge
  28:              ,airport_fee
  29:              )
  30:                SELECT 
  31:                VendorID,
  32:              tpep_pickup_datetime,
  33:              tpep_dropoff_datetime,
  34:              passenger_count,
  35:              trip_distance,
  36:              RatecodeID,
  37:              store_and_fwd_flag,
  38:              PULocationID,
  39:              DOLocationID,
  40:              payment_type,
  41:              fare_amount,
  42:              extra,
  43:              mta_tax,
  44:              tip_amount,
  45:              tolls_amount,
  46:              improvement_surcharge,
  47:              total_amount,
  48:              congestion_surcharge,
  49:              CAST(airport_fee AS FLOAT64) as airport_fee
  50:            FROM polynomial-land.trips_data_all.temp_table;
  51:  
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
[2022-09-02 13:50:09,891] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-09-02 13:50:09,913] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
